# Generated by Django 5.0.2 on 2024-02-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_tagpost_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
