# Generated by Django 5.0.2 on 2024-02-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_article_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagPost',
            new_name='TagArticle',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='web.tagarticle', verbose_name='Теги'),
        ),
    ]
