# Generated by Django 5.0.2 on 2024-02-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_tagarticle_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
