# Generated by Django 5.0.2 on 2024-02-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rename_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.BooleanField(choices=[(0, 'Пользователь'), (1, 'Эксперт')], default=0, verbose_name='Категория пользователя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
