# Generated by Django 5.0.2 on 2024-03-01 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_customuser_is_active_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=2000)),
                ('education', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('hour_cost', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expertprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
