# Generated by Django 5.0.2 on 2024-03-04 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_expertprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='cat',
            field=models.ForeignKey(blank=True,  on_delete=django.db.models.deletion.PROTECT, related_name='questionanswer', to='web.category', verbose_name='Категории'),
            preserve_default=False,
        ),
    ]
