# Generated by Django 5.0.2 on 2024-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_questionanswer_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.customuser',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Пользователь'), (1, 'Эксперт')], default=0, verbose_name='Категория пользователя'),
        ),
    ]
