# Generated by Django 5.0.2 on 2024-03-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_expert_alter_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
