# Generated by Django 5.0.3 on 2024-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_expertprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
