# Generated by Django 5.0.2 on 2024-03-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
