# Generated by Django 5.0.2 on 2024-04-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_article_description_alter_article_main_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivation',
        ),
    ]
