# Generated by Django 5.0.3 on 2024-04-01 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_article_description_alter_article_main_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Неверифицирован'), (1, 'Верифицирован')], default=0, verbose_name='Статус проверки Эксперта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to=settings.AUTH_USER_MODEL),
        ),
    ]
