# Generated by Django 5.0.2 on 2024-04-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_expertprofile_status_alter_article_author'),
        ('web', '0026_customuser_phone_number'),
    ]

    operations = [
    ]
