# Generated by Django 5.0.2 on 2024-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_merge_20240401_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='is_verified',
            field=models.IntegerField(choices=[(0, 'Неверифицирован'), (1, 'Верифицирован')], default=0, verbose_name='Expert verification status'),
        ),
    ]
