# Generated by Django 5.0.3 on 2024-04-08 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonVerifiedExpert',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.customuser',),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='expert_categories',
            field=models.ManyToManyField(related_name='categories', to='web.category'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79997654321'. Up to 15 digits allowed.", regex='^((8|\\+374|\\+994|\\+995|\\+375|\\+7|\\+380|\\+38|\\+996|\\+998|\\+993)[\\- ]?)?\\(?\\d{3,5}\\)?[\\- ]?\\d{1}[\\- ]?\\d{1}[\\- ]?\\d{1}[\\- ]?\\d{1}[\\- ]?\\d{1}(([\\- ]?\\d{1})?[\\- ]?\\d{1})?$')], verbose_name='phone number'),
        ),
    ]
