# Generated by Django 5.0.3 on 2024-04-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_nonverifiedexpert_expertprofile_expert_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='expert_categories',
            field=models.ManyToManyField(to='web.category'),
        ),
    ]
