# Generated by Django 5.0.3 on 2024-04-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_nonverifiedexpert_alter_customuser_phone_number'),
        ('web', '0034_alter_customuser_phone_number'),
    ]

    operations = [
    ]
