# Generated by Django 5.0.2 on 2024-05-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_merge_20240424_0729'),
        ('web', '0033_merge_20240424_1455'),
        ('web', '0037_article_allow_comments'),
    ]

    operations = [
    ]
