# Generated by Django 5.0.4 on 2024-05-08 05:56

import django.db.models.deletion
import web.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_article_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='hh_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на HH'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на LinkedIn'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=web.models.users.UploadToPathAndRename('documents'), verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('expertprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.expertprofile')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='certification_documents',
            field=models.ManyToManyField(blank=True, related_name='certification_documents', to='web.document', verbose_name='Сертификаты об образовании'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='degree_documents',
            field=models.ManyToManyField(blank=True, related_name='degree_documents', to='web.document', verbose_name='Дипломы об образовании'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='experience_documents',
            field=models.ManyToManyField(blank=True, related_name='experience_documents', to='web.document', verbose_name='Документы подтверждающие стаж'),
        ),
    ]
