# Generated by Django 5.0.4 on 2024-05-10 07:31

import web.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_expertprofile_hh_link_expertprofile_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='educational_institution',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='number_diploma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='specialized_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=web.models.users.UploadToPathAndRename('expert/documents'), verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of upload'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='degree_documents',
            field=models.ManyToManyField(blank=True, related_name='degree_documents', to='web.document', verbose_name='Education documents'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='education',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='experience_documents',
            field=models.ManyToManyField(blank=True, related_name='experience_documents', to='web.document', verbose_name='Documents confirming experience'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='hh_link',
            field=models.URLField(blank=True, verbose_name='Link to HH'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='is_verified',
            field=models.IntegerField(choices=[(0, 'Unverified'), (1, 'Verified')], default=0, verbose_name='Expert verification status'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, verbose_name='Link to LinkedIn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/profile_picture_icon.png', upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Client'), (1, 'Expert')], default=0, verbose_name='Category user'),
        ),
    ]
