# Generated by Django 5.0.4 on 2024-05-14 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_expertprofile_educational_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='expertprofile',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='degree_documents',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='educational_institution',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='number_diploma',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='specialized_education',
        ),
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('primary', 'Primary'), ('additional', 'Additional')], default='primary', max_length=10, verbose_name='Education Type')),
                ('specialized_education', models.BooleanField(default=False)),
                ('educational_institution', models.CharField(blank=True, max_length=250, null=True, verbose_name='Educational Institution')),
                ('educational_institution_verified', models.BooleanField(default=False)),
                ('diploma_number', models.IntegerField(blank=True, null=True, verbose_name='Educational Institution')),
                ('diploma_number_verified', models.BooleanField(default=False)),
                ('degree_documents', models.ManyToManyField(blank=True, related_name='degree_documents', to='web.document', verbose_name='Education documents')),
                ('expert_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='web.expertprofile')),
            ],
        ),
    ]
