# Generated by Django 5.0.4 on 2024-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_remove_document_expertprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='consulting_experience',
            field=models.IntegerField(default=0),
        ),
    ]
