# Generated by Django 5.0.4 on 2024-05-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_expertprofile_consulting_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
