# Generated by Django 5.0.4 on 2024-05-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_expertprofile_consulting_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAnketa',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.expertprofile',),
        ),
        migrations.CreateModel(
            name='ExpertVerifiedProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.expertprofile',),
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='education',
            name='degree_documents',
        ),
        migrations.RemoveField(
            model_name='education',
            name='diploma_number_verified',
        ),
        migrations.RemoveField(
            model_name='education',
            name='educational_institution_verified',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='experience_documents',
        ),
        migrations.AddField(
            model_name='document',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degree_documents', to='web.education'),
        ),
        migrations.AddField(
            model_name='document',
            name='expert_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.expertprofile'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='type_profile',
            field=models.IntegerField(choices=[(0, 'Anketa'), (1, 'Verified Profile')], default=0, verbose_name='Profile status'),
        ),
    ]
