# Generated by Django 5.0.4 on 2024-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_expertanketa_expertverifiedprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertAnketa',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='type_profile',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='anketa',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
