# Generated by Django 5.0.4 on 2024-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_ratingrole_ratingcalculate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ratingcalculate',
            constraint=models.UniqueConstraint(fields=('role', 'user'), name='unique_role_user'),
        ),
    ]
