# Generated by Django 5.0.3 on 2024-06-07 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_ratingrole_ratingcalculate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAnketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=2000, null=True)),
                ('age', models.IntegerField(null=True)),
                ('hour_cost', models.IntegerField(null=True)),
                ('consulting_experience', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('hh_link', models.URLField(blank=True, verbose_name='Link to HH')),
                ('linkedin_link', models.URLField(blank=True, verbose_name='Link to LinkedIn')),
                ('is_verified', models.IntegerField(choices=[(0, 'Unverified'), (1, 'Verified')], default=0, verbose_name='Expert verification status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ExpertVerifiedProfile',
        ),
        migrations.DeleteModel(
            name='NonVerifiedExpert',
        ),
        migrations.RemoveField(
            model_name='document',
            name='expert_profile',
        ),
        migrations.RemoveField(
            model_name='education',
            name='expert_profile',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='anketa',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='documents',
            field=models.ManyToManyField(to='web.document'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='education',
            field=models.ManyToManyField(to='web.education'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='expert_categories',
            field=models.ManyToManyField(to='web.category'),
        ),
        migrations.AddField(
            model_name='expertanketa',
            name='documents',
            field=models.ManyToManyField(to='web.document'),
        ),
        migrations.AddField(
            model_name='expertanketa',
            name='education',
            field=models.ManyToManyField(to='web.education'),
        ),
        migrations.AddField(
            model_name='expertanketa',
            name='expert_categories',
            field=models.ManyToManyField(to='web.category'),
        ),
        migrations.AddField(
            model_name='expertanketa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expertanketa', to=settings.AUTH_USER_MODEL),
        ),
    ]
