# Generated by Django 5.0.6 on 2024-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_ratingcalculate_unique_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='styles',
            field=models.TextField(null=True),
        ),
    ]
