# Generated by Django 5.0.4 on 2024-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_article_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='styles',
            field=models.TextField(blank=True, null=True, verbose_name='Стили'),
        ),
    ]
