# Generated by Django 5.0.3 on 2024-04-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbappointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'Верифицирован'), (2, 'Верифицирован'), (3, 'Верифицирован'), (4, 'Верифицирован')], default=0),
        ),
        migrations.CreateModel(
            name='AppointmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Ожидание'), (1, 'Оплачено'), (2, 'Отменено')], default=0)),
                ('uuid', models.UUIDField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='wbappointment.appointment')),
            ],
        ),
    ]
