# Generated by Django 5.0.3 on 2024-04-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbappointment', '0003_expertschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'Подтвержден'), (2, 'Отклонен'), (3, 'Отменен'), (4, 'Оплачен')], default=0),
        ),
    ]
