# Generated by Django 5.0.4 on 2024-05-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbappointment', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
