# Generated by Django 5.0.3 on 2024-05-10 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbappointment', '0005_alter_expertschedule_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertScheduleSpecialDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')])),
            ],
        ),
        migrations.AddField(
            model_name='expertschedule',
            name='is_work_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='expertschedule',
            constraint=models.UniqueConstraint(fields=('expert', 'day_of_week'), name='unique_experts_schedule'),
        ),
        migrations.AddField(
            model_name='expertschedulespecialdays',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_expert', to=settings.AUTH_USER_MODEL),
        ),
    ]
