# Generated by Django 5.0.6 on 2024-08-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbappointment', '0007_remove_appointment_unique_experts_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='expertschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='expertschedule',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='expertschedule',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
