# Generated by Django 5.0.2 on 2024-04-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertprojects', '0002_alter_userproject_member_delete_userprojectmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='category',
        ),
        migrations.AddField(
            model_name='userproject',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='userprojects', to='expertprojects.category', verbose_name='Категории'),
        ),
    ]
