# Generated by Django 5.0.2 on 2024-04-08 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertprojects', '0003_remove_userproject_category_userproject_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userproject', to='expertprojects.userprojectfile'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='category',
            field=models.ManyToManyField(related_name='userprojects', to='expertprojects.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userproject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprojectfile',
            name='file',
            field=models.FileField(upload_to='expert/projects/%Y/%m/%d/'),
        ),
    ]
