# Generated by Django 5.0.2 on 2024-04-09 04:45

import django.db.models.deletion
import expertprojects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertprojects', '0004_userproject_file_alter_userproject_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='file',
        ),
        migrations.AlterField(
            model_name='userprojectfile',
            name='file',
            field=models.FileField(upload_to='expert/projects/%Y/%m/%d/', validators=[expertprojects.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='userprojectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='expertprojects.userproject'),
        ),
    ]
