# Generated by Django 5.0.2 on 2024-04-17 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertprojects', '0005_remove_userproject_file_alter_userprojectfile_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproject',
            old_name='member',
            new_name='author',
        ),
        migrations.AddField(
            model_name='userproject',
            name='members',
            field=models.ManyToManyField(related_name='userprojects', to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта'),
        ),
    ]
