# Generated by Django 5.0.2 on 2024-04-29 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertprojects', '0006_rename_member_userproject_author_userproject_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='members',
            field=models.ManyToManyField(related_name='userprojects', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
