# Generated by Django 5.0.4 on 2024-05-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertprojects', '0009_alter_userproject_author_alter_userproject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='company',
            field=models.CharField(default='ООО', max_length=255, verbose_name='Company'),
        ),
    ]
